services:
  - type: web
    name: anime-sama-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: API_BASE_URL
        sync: false
    autoDeploy: false