services:
  - type: web
    name: anime-sama-app
    env: node
    plan: free
    buildCommand: npm ci && npx vite build --config vite.config.ts && npx esbuild server/index-production.ts --platform=node --packages=external --bundle --format=esm --outdir=dist && mkdir -p dist/public && cp -r client/dist/* dist/public/ && npm run db:push
    startCommand: node dist/index-production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: API_BASE_URL
        sync: false
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_mtSpzriYuV56@ep-round-lake-a8zn7f2c-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    autoDeploy: false