services:
  - type: web
    name: otaku-nexus
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: otaku-nexus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: false
    
databases:
  - name: otaku-nexus-db
    databaseName: otaku_nexus
    user: otaku_user
    plan: starter