services:
  - type: web
    name: otaku-nexus
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://api-anime-sama.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: otaku-nexus-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true
    
databases:
  - name: otaku-nexus-db
    databaseName: otaku_nexus
    user: otaku_user
    plan: starter