services:
  # Application Web principale
  - type: web
    name: otaku-nexus
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: otaku-nexus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    autoDeploy: true

  # Base de données PostgreSQL
databases:
  - name: otaku-nexus-db
    databaseName: otaku_nexus
    user: otaku_nexus_user
    plan: starter