export const animalAnimeData = [
  {
    malId: 205,
    title: "Samurai Champloo",
    synopsis: "Mugen is a ferocious, animalistic warrior with a fighting style inspired by break-dancing. Jin is a ronin samurai who wanders the countryside alone. They may not be friends, but their paths continually cross. And when ditzy waitress Fuu gets them out of hot water with the local magistrate, they agree to join her search for the samurai who smells like sunflowers.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/11/20883.jpg",
    score: "8.5",
    year: 2004,
    status: "Finished Airing",
    episodes: 26,
    genres: ["Action", "Adventure", "Comedy", "Drama", "Historical", "Samurai"],
    hasAnimals: true,
    animalTypes: ["Dogs", "Birds", "Insects"]
  },
  {
    malId: 1,
    title: "Cowboy Bebop",
    synopsis: "In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as Cowboys. The ragtag team aboard the spaceship Bebop are two such individuals.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/4/19644.jpg",
    score: "8.78",
    year: 1998,
    status: "Finished Airing",
    episodes: 26,
    genres: ["Action", "Adventure", "Drama", "Sci-Fi", "Space"],
    hasAnimals: true,
    animalTypes: ["Dogs", "Birds", "Fish"]
  },
  {
    malId: 40748,
    title: "Jujutsu Kaisen",
    synopsis: "Idly indulging in baseless paranormal activities with the Occult Club, high schooler Yuuji Itadori spends his days at either the clubroom or the hospital, where he visits his bedridden grandfather. However, this leisurely lifestyle soon takes a turn for the strange when he unknowingly encounters a cursed item.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    score: "8.5",
    year: 2020,
    status: "Finished Airing",
    episodes: 24,
    genres: ["Action", "School", "Shounen", "Supernatural"],
    hasAnimals: true,
    animalTypes: ["Cursed Animals", "Spirit Animals", "Mythical Creatures"]
  },
  {
    malId: 42938,
    title: "Fruits Basket: The Final",
    synopsis: "Hundreds of years ago, the Chinese Zodiac spirits and their god swore to stay together eternally. United by this promise, the possessed members of the Souma family shall always return to each other under any circumstances. Yet, when these bonds shatter, the consequences are catastrophic.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1085/99667.jpg",
    score: "9.0",
    year: 2021,
    status: "Finished Airing",
    episodes: 13,
    genres: ["Drama", "Romance", "Shoujo", "Slice of Life", "Supernatural"],
    hasAnimals: true,
    animalTypes: ["Zodiac Animals", "Cats", "Dogs", "Rabbits", "Tigers"]
  },
  {
    malId: 39587,
    title: "Beastars",
    synopsis: "In a civilized society of anthropomorphic animals, an uneasy tension exists between carnivores and herbivores. At Cherryton Academy, this mutual distrust peaks after a murder incident results in the death of Tem, an alpaca in the school's drama club.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1312/99914.jpg",
    score: "7.8",
    year: 2019,
    status: "Finished Airing",
    episodes: 12,
    genres: ["Drama", "Mystery", "School", "Slice of Life"],
    hasAnimals: true,
    animalTypes: ["Wolves", "Rabbits", "Lions", "Bears", "Deer", "All Animals"]
  },
  {
    malId: 431,
    title: "Howl's Moving Castle",
    synopsis: "That jumbled piece of architecture, that cacophony of hissing steam and creaking joints, with smoke billowing from it as it moves on its own... That castle is home to the magnificent wizard Howl, infamous for both his magical prowess and for being a womanizer.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/75810.jpg",
    score: "8.66",
    year: 2004,
    status: "Finished Airing",
    episodes: 1,
    genres: ["Adventure", "Drama", "Family", "Romance", "Supernatural"],
    hasAnimals: true,
    animalTypes: ["Dogs", "Birds", "Magical Creatures"]
  },
  {
    malId: 164,
    title: "Mononoke Hime",
    synopsis: "When an Emishi village is attacked by a fierce demon boar, the young prince Ashitaka puts his life at stake to defend his tribe. With its dying breath, the beast curses the prince's arm, granting him demonic powers while gradually siphoning his life away.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/7/75919.jpg",
    score: "8.7",
    year: 1997,
    status: "Finished Airing",
    episodes: 1,
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    hasAnimals: true,
    animalTypes: ["Wolves", "Boars", "Forest Spirits", "Deer"]
  },
  {
    malId: 1482,
    title: "D.Gray-man",
    synopsis: "Toward the end of the 19th century, Allen Walker officially joins the organization of Exorcists that destroy the beings known as Akuma; mechanic weapons made by the Millennium Earl with the suffering souls of the dead.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/2/21319.jpg",
    score: "8.0",
    year: 2006,
    status: "Finished Airing",
    episodes: 103,
    genres: ["Action", "Adventure", "Historical", "Shounen", "Supernatural"],
    hasAnimals: true,
    animalTypes: ["Cats", "Birds", "Mythical Creatures"]
  },
  {
    malId: 22729,
    title: "Barakamon",
    synopsis: "As a punishment for punching a famous calligrapher, young handsome calligrapher Handa Seishu is exiled to a small island. As someone who has never lived outside of a city, Handa has to adapt to his new wacky neighbors, like people traveling on a tractor, unwanted visitors who never use the front door, annoying kids using his home as a playground, etc.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/64513.jpg",
    score: "8.3",
    year: 2014,
    status: "Finished Airing",
    episodes: 12,
    genres: ["Comedy", "Slice of Life"],
    hasAnimals: true,
    animalTypes: ["Cats", "Insects", "Sea Creatures"]
  },
  {
    malId: 11061,
    title: "Hunter x Hunter (2011)",
    synopsis: "Hunter x Hunter is set in a world where Hunters, licensed individuals with exceptional skills, embark on dangerous tasks like capturing criminals and searching for rare treasures. Twelve-year-old Gon Freecss dreams of becoming a Hunter to find his father, who abandoned him for this profession.",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1440/88652.jpg",
    score: "9.0",
    year: 2011,
    status: "Finished Airing",
    episodes: 148,
    genres: ["Action", "Adventure", "Fantasy", "Shounen"],
    hasAnimals: true,
    animalTypes: ["Magical Beasts", "Chimera Ants", "Various Creatures"]
  }
];